# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfa8c28f8f0fb1898338f9e55f3379b9e78024d86ebe0ab8d6fe7220c2d002b68e92ebbf8811d2300d10dafee0d7afe9d8f00a91824f0450f3b1604d438c7721

test:
  secret_key_base: c8cd91dca2168cea5247c1a32e611e7398de82adb95492510cd0f57b0e96bc45c2d63e530312ef90cdc801e56706250ba034a8a7e5326d1b5dcc6d0ec0183f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
